name: Go Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.4-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: apk add --no-cache git bash

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./...
